spring:
  application:
    name: SERVICE-HEALTHANALYZER
  datasource:
    url: jdbc:postgresql://localhost:5432/bd-healthanalyzer
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update # o create-drop si quieres reiniciar la BD cada vez
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5673
    username: admin
    password: admin

server:
  port: 8099

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: health,info

